# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: CI Build
    outputs:
      shouldPublish: ${{ steps.shouldPublish.outputs.shouldPublish }}

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Use Node.js v14.x
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      # install dependencies
      - run: npm install

      # run build
      - run: npm run dev:no-watch

      # run tests
      - run: npm run test
        env:
          CI: true

      # upload test code coverage to codecov
      - name: Codecov
        uses: codecov/codecov-action@v1.0.15
        with:
          token: 65a53498-2a23-4a44-ace0-0adb07586906

      # Check if publishing job should run - this avoid continually triggering CI actions when the bot commits the version bump change
      - name: Should publish Check
        id: shouldPublish
        run: |
          LASTAUTHOR=$(git log -1 --pretty=format:'%an')
          if [ $LASTAUTHOR = "dominion-world-bot" ]; then
            echo "::set-output name=shouldPublish::false"
          else
            echo "::set-output name=shouldPublish::true"
          fi

  publish:
    name: Publish build
    needs: build
    if: github.ref == 'refs/heads/main' && needs.build.outputs.shouldPublish == 'true'
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Use Node.js v14.x
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      # install dependencies
      - run: npm install

      # Setup bot information for commiting the version bumps
      - name: Setup bot git information
        run: |
          git config user.email "dominion-world-bot@wow-i-am-a-bot.com"
          git config user.name "dominion-world-bot"

      # Bump version numbers if on main CI branch
      - name: Bump verison numbers
        run: npm run bump

      # Run prod build and packaging
      - run: npm run package

      # Create a datetime variable to use as a release name
      - name: Get Release names
        id: releasenames
        run: |
          echo "::set-output name=tagname::$(date +'%Y-%m-%d-%H%M')"
          echo "::set-output name=releasename::$(TZ=":America/Vancouver" date +'%Y-%m-%d %H%M')"

      # Upload package that can be submitted to store
      - name: Upload Package
        uses: softprops/action-gh-release@v1
        with:
          files: DominionWorld Chromium Extension.zip
          name: DominionWorld Chromium Extension Package ${{ steps.releasenames.outputs.releasename }}
          tag_name: Release/${{ steps.releasenames.outputs.tagname }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Push the version bump changes to main after publishing was successful
      - name: Push bumping changes back to main
        run: |
          git add .
          git commit -m "Bump versions"
          git push origin main
