# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Use Node.js v14.x
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - run: npm install
      
      # run build
      - run: npm run dev:no-watch
      - run: npm run package
      
      # run tests
      - run: npm run test
        env:
          CI: true
      
      # upload test code coverage to codecov
      - name: Codecov
        uses: codecov/codecov-action@v1.0.15
        with:
          token: 65a53498-2a23-4a44-ace0-0adb07586906

      - name: Get Release names
        if: github.ref == 'refs/heads/main'
        id: releasenames
        run: |
          echo "::set-output name=tagname::$(date +'%Y-%m-%d-%H%M')"
          echo "::set-output name=releasename::$(TZ=":America/Vancouver" date +'%Y-%m-%d %H%M')"

      - name: Upload Package
        if: github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v1
        with:
          files: DominionWorld Chromium Extension.zip
          name: DominionWorld Chromium Extension Package ${{ steps.releasenames.outputs.releasename }}
          tag_name: Release/${{ steps.releasenames.outputs.releasename }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
