name: Sync issue to Azure DevOps work item

on:
  issues:
    types:
      [opened, edited, deleted, closed, reopened, labeled, unlabeled, assigned]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  alert:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Issues to Azure DevOps
        uses: danhellem/github-actions-issue-to-work-item@1.6
        env:
          ado_token: "${{ secrets.ADO_PERSONAL_ACCESS_TOKEN }}"
          github_token: "${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}"
          ado_organization: "jaburnsi"
          ado_project: "scripts"
          ado_wit: "Issue"
          ado_new_state: "To Do"
          ado_active_state: "Doing"
          ado_close_state: "Done"
          ado_bypassrules: true
